### ISSUE TITLE
Idea: Including the code in the README

### ISSUE THREAD

**Issue by ptrkrlsrd** [cornelk/go-benchmark#5]
Having examples in the README under each benchmark would make it a lot easier to see what each benchmark does. 

Example:

```
Using defer vs not using it

BenchmarkDefer-8                           	   20000	     58155 ns/op
BenchmarkDeferNo-8                         	  300000	      5378 ns/op
```  

*Defer*
```
defer checkItem(b, i, item)
```

*No defer*
``` 
checkItem(b, i, item)
```

This approach might make it a bit more messy, so another solution could be to at least provide the links to each file used in the benchmarks for easier navigation.

Anyways, great job providing this! I think people will get much use of these benchmarks

**Comment by cornelk** [comment]
I decided against it as it would bloat the readme too much.
